### PR TITLE
Nicer folding

### PR DESCRIPTION
**Pull request by alehandrof**
This is a slightly half-baked attempt to address #12.

I've incorporated @vovkkk's code and improved the handling of Ctrl/Cmd+Enter, but it's still problematic in the following cases:
- When word wrap is on and the fold marker is on its own line.

```
# Heading 1
[...]
Et cetera
```
- There is only one heading and the rest of the document is folded.

```
# Heading 1[...]
```

### CODE REVIEW

**Comment by vovkkk** [comment]
> When word wrap is on and the fold marker is on its own line.
> 
> ```
> # Heading 1
> [...]
> Et cetera
> ```

I can't reproduce it (I even tried switch between automatic and column based wrap)

**Comment by alehandrof** [comment]
Here's a screencast reproducing this case on ST 3022: http://db.tt/2vn9pojf
Are you on Sublime 2, perhaps?

**Comment by vovkkk** [comment]
Doh, I just misunderstood that you told about wrapped header.
Yes, ST2 behave identically, but I'm not sure we can do anything about it.

In screencast you typed 'This is also a problem:(' - could you please explain? same ctrl+enter issue or something else?

**Comment by alehandrof** [comment]
This is the 2nd issue I mention in the pull request. It occurs when you try to Ctrl+Enter on the last heading (or there is only one heading) when the rest of the document is folded underneath it.

**Comment by vovkkk** [comment]
There is move_to eof - end of file (and it works), but I don't see ability to add any logic in macro.
Probably it should be implemented in Python.

**Pull request merged**
